window.CONVERTER_CONFIGS = [
    {
        id: "doc-to-pdf",
        tone: "doc",
        badge: "DOC",
        title: "DOC to PDF",
        shortLabel: "DOC file",
        description: "Turn Word documents into polished PDF output with a clean delivery flow.",
        heading: "Upload your DOC or DOCX file",
        accept: [".doc", ".docx"],
        endpoint: "/doc-to-pdf/",
        outputLabel: "PDF",
    },
    {
        id: "doc-to-txt",
        tone: "txt",
        badge: "TXT",
        title: "DOC to TXT",
        shortLabel: "DOC file",
        description: "Extract readable plain text from Word content in a minimal, fast output format.",
        heading: "Upload your DOC or DOCX file",
        accept: [".doc", ".docx"],
        endpoint: "/doc-to-txt/",
        outputLabel: "TXT",
    },
    {
        id: "excel-to-pdf",
        tone: "sheet",
        badge: "XLS",
        title: "Excel to PDF",
        shortLabel: "Excel sheet",
        description: "Flatten spreadsheets into easy-to-share PDF documents for reporting and review.",
        heading: "Upload your XLS or XLSX file",
        accept: [".xls", ".xlsx"],
        endpoint: "/excel-to-pdf/",
        outputLabel: "PDF",
    },
    {
        id: "csv-to-excel",
        tone: "data",
        badge: "CSV",
        title: "CSV to Excel",
        shortLabel: "CSV file",
        description: "Take raw comma-separated data and package it into an Excel workbook.",
        heading: "Upload your CSV file",
        accept: [".csv"],
        endpoint: "/csv-to-excel/",
        outputLabel: "XLSX",
    },
    {
        id: "image-to-pdf",
        tone: "image",
        badge: "IMG",
        title: "Image to PDF",
        shortLabel: "image",
        description: "Bundle a PNG or JPEG into clean PDF output for quick sharing and submission.",
        heading: "Upload your PNG or JPEG file",
        accept: [".png", ".jpeg", ".jpg"],
        endpoint: "/image-to-pdf/",
        outputLabel: "PDF",
    },
    {
        id: "odt-to-pdf",
        tone: "odt",
        badge: "ODT",
        title: "ODT to PDF",
        shortLabel: "ODT file",
        description: "Convert OpenDocument text files into stable PDF output in the same workspace.",
        heading: "Upload your ODT file",
        accept: [".odt"],
        endpoint: "/odt-to-pdf/",
        outputLabel: "PDF",
    },
];
